package com.dede.domain.model;

public enum NodeType {
    PROJECT,
    PACKAGE,
    CLASS,
    INTERFACE,
    METHOD,
    FIELD,
    BUNDLE,
    OSGI_SERVICE,
    OSGI_COMPONENT,
    OSGI_CONFIG,
    JCR_RESOURCE_TYPE,
    SLING_MODEL,
    HTL_FILE,
    CLIENTLIB,
    VULNERABILITY,
    SLING_CACONFIG,
    OSGI_CONFIG_FACTORY,
    WORKFLOW_PROCESS,
    SLING_JOB,
    JCR_PAGE,
    JCR_COMPONENT,
    DISPATCHER_FILTER,
    CDN_RULE,
    CONTENT_PACKAGE,
    PACKAGE_VIOLATION,

    // Sling Request Processing types
    SLING_SERVLET,
    SLING_FILTER,
    SLING_SELECTOR,
    SLING_EXTENSION,
    SLING_PATH,
    SLING_FILTER_SCOPE
}
